language: go
env:
  global:
  - gimme 1.6
  matrix:
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=linux GIMME_ARCH=386
  - GIMME_OS=linux GIMME_ARCH=arm
  - GIMME_OS=linux GIMME_ARCH=arm64
  - GIMME_OS=linux GIMME_ARCH=ppc64
  - GIMME_OS=darwin GIMME_ARCH=amd64
  - GIMME_OS=darwin GIMME_ARCH=386
  - GIMME_OS=darwin GIMME_ARCH=arm
  - GIMME_OS=darwin GIMME_ARCH=arm64
  - GIMME_OS=windows GIMME_ARCH=amd64
  - GIMME_OS=windows GIMME_ARCH=386
  - GIMME_OS=windows GIMME_ARCH=arm
  - GIMME_OS=freebsd GIMME_ARCH=amd64
  - GIMME_OS=freebsd GIMME_ARCH=386
  - GIMME_OS=freebsd GIMME_ARCH=arm
install:
- printenv
- go generate
script:
- go test -v ./...
- if [[ $TRAVIS_BRANCH == v* ]]; then go build -v -ldflags '-extldflags "-static"' -o "fence_${GIMME_OS}_${GIMME_ARCH}${EXT}"; fi
- ls
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: CrvRmjoiEPTWIPWw4BrU1YiZQ9WGkzi7WIOxfCmNnyLcg/a6QVo5CV1vRyTKOY/JEnlU8PusEMgOX81sMIOpyaMHfLpR/ca7UzMp61MzCJ2Yah0Lw7kTJjT+cw5HB12OgxfED51XI9wQjgC+ByaLSH1oS25Md0GbLf0qRHCbLYaNDckw/EgbVNWZTDqUacJJFJcR8tbXYxsUXvBLJda8aPrGjiRaonj6gRjzDMQR2qFeX/kmOOzmIoa17jW9rpqj+G686FvDkyeoeBFFlS8YK8zeViclbpM3gpnpV+HdEixIKRP/gndoH0Tx90DPC64RJj3mibywWffG33RhYKx1twkbJGCU47tRzIapAdzSR4dmUL3rb0W3oJm7GY5IHLcOYWNFWVFRszOIySkM1hXVxbTWwZYZrEFaC9hFDAKB7A4X3D+SAFqseab16XB005RqrUDHAB1uLO03uivRbGWTj7s5I6i+JQfm9ps5UwcVrJm2xWlYFnqjl37rAfZgxXCADYOBjw6PbKF+xJjLvLd4kAEkSQ+siZvKoCBWLNfmmYFZGMWnj0BPFoPot/VDOFKklmTb+FcdyiZ2HFhjojIjkNpHWbNtWwuK0UcEHVm+lCx0K+GqMpz4T7S+dJoDVJBnGmSmiovC37UIwtFnRwnalq6O2Q332ghoFPQyPHzsuls=
  file: fence_${GIMME_OS}_${GIMME_ARCH}${EXT}
  on:
    repo: buckhx/gofence
    tags: true
