language: go
go:
  - 1.6
install:
- printenv
- go get github.com/mitchellh/gox
- go generate
script:
- go test -v ./...
- if [[ $TRAVIS_BRANCH == v* ]]; then gox -verbose -output="fence_{{.OS}}_{{.Arch}}" -ldflags '-extldflags "-static"'; fi
- ls
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: CrvRmjoiEPTWIPWw4BrU1YiZQ9WGkzi7WIOxfCmNnyLcg/a6QVo5CV1vRyTKOY/JEnlU8PusEMgOX81sMIOpyaMHfLpR/ca7UzMp61MzCJ2Yah0Lw7kTJjT+cw5HB12OgxfED51XI9wQjgC+ByaLSH1oS25Md0GbLf0qRHCbLYaNDckw/EgbVNWZTDqUacJJFJcR8tbXYxsUXvBLJda8aPrGjiRaonj6gRjzDMQR2qFeX/kmOOzmIoa17jW9rpqj+G686FvDkyeoeBFFlS8YK8zeViclbpM3gpnpV+HdEixIKRP/gndoH0Tx90DPC64RJj3mibywWffG33RhYKx1twkbJGCU47tRzIapAdzSR4dmUL3rb0W3oJm7GY5IHLcOYWNFWVFRszOIySkM1hXVxbTWwZYZrEFaC9hFDAKB7A4X3D+SAFqseab16XB005RqrUDHAB1uLO03uivRbGWTj7s5I6i+JQfm9ps5UwcVrJm2xWlYFnqjl37rAfZgxXCADYOBjw6PbKF+xJjLvLd4kAEkSQ+siZvKoCBWLNfmmYFZGMWnj0BPFoPot/VDOFKklmTb+FcdyiZ2HFhjojIjkNpHWbNtWwuK0UcEHVm+lCx0K+GqMpz4T7S+dJoDVJBnGmSmiovC37UIwtFnRwnalq6O2Q332ghoFPQyPHzsuls=
  file:
    - "fence_darwin_386"
    - "fence_darwin_amd64"
    - "fence_linux_386"
    - "fence_linux_amd64"
    - "fence_linux_arm"
    - "fence_freebsd_386"
    - "fence_freebsd_amd64"
    - "fence_freebsd_arm"
    - "fence_openbsd_386"
    - "fence_openbsd_amd64"
    - "fence_windows_386"
    - "fence_windows_amd64"
    - "fence_netbsd_386"
    - "fence_netbsd_amd64"
    - "fence_netbsd_arm"
  on:
    repo: buckhx/gofence
    tags: true
